# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mrgaze/gui/MrGaze/mrgaze.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MrGaze(object):
    def setupUi(self, MrGaze):
        MrGaze.setObjectName("MrGaze")
        MrGaze.resize(589, 433)
        self.centralWidget = QtWidgets.QWidget(MrGaze)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 230, 571, 141))
        self.tabWidget.setObjectName("tabWidget")
        self.Setup_Tab = QtWidgets.QWidget()
        self.Setup_Tab.setObjectName("Setup_Tab")
        self.Intensity_LB_Dial = QtWidgets.QDial(self.Setup_Tab)
        self.Intensity_LB_Dial.setGeometry(QtCore.QRect(10, 10, 71, 71))
        self.Intensity_LB_Dial.setMaximum(100)
        self.Intensity_LB_Dial.setNotchTarget(5.0)
        self.Intensity_LB_Dial.setNotchesVisible(True)
        self.Intensity_LB_Dial.setObjectName("Intensity_LB_Dial")
        self.Intensity_UB_Dial = QtWidgets.QDial(self.Setup_Tab)
        self.Intensity_UB_Dial.setGeometry(QtCore.QRect(90, 10, 71, 71))
        self.Intensity_UB_Dial.setMaximum(100)
        self.Intensity_UB_Dial.setProperty("value", 100)
        self.Intensity_UB_Dial.setNotchTarget(5.0)
        self.Intensity_UB_Dial.setNotchesVisible(True)
        self.Intensity_UB_Dial.setObjectName("Intensity_UB_Dial")
        self.Intensity_LB_Label = QtWidgets.QLabel(self.Setup_Tab)
        self.Intensity_LB_Label.setGeometry(QtCore.QRect(10, 80, 71, 20))
        self.Intensity_LB_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Intensity_LB_Label.setObjectName("Intensity_LB_Label")
        self.Intensity_UB_Label = QtWidgets.QLabel(self.Setup_Tab)
        self.Intensity_UB_Label.setGeometry(QtCore.QRect(90, 80, 71, 20))
        self.Intensity_UB_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Intensity_UB_Label.setObjectName("Intensity_UB_Label")
        self.comboBox = QtWidgets.QComboBox(self.Setup_Tab)
        self.comboBox.setGeometry(QtCore.QRect(282, 5, 151, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.Setup_Tab)
        self.pushButton.setGeometry(QtCore.QRect(450, 70, 111, 32))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.Setup_Tab)
        self.label.setGeometry(QtCore.QRect(180, 10, 91, 21))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.Setup_Tab)
        self.label_2.setGeometry(QtCore.QRect(180, 40, 91, 21))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.Setup_Tab)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 70, 113, 32))
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.toolButton = QtWidgets.QToolButton(self.Setup_Tab)
        self.toolButton.setGeometry(QtCore.QRect(280, 40, 26, 22))
        self.toolButton.setObjectName("toolButton")
        self.tabWidget.addTab(self.Setup_Tab, "")
        self.Calibrate_Tab = QtWidgets.QWidget()
        self.Calibrate_Tab.setObjectName("Calibrate_Tab")
        self.tabWidget.addTab(self.Calibrate_Tab, "")
        self.Gaze_Tab = QtWidgets.QWidget()
        self.Gaze_Tab.setObjectName("Gaze_Tab")
        self.tabWidget.addTab(self.Gaze_Tab, "")
        self.Video = QtWidgets.QLabel(self.centralWidget)
        self.Video.setGeometry(QtCore.QRect(10, 10, 281, 211))
        self.Video.setFrameShape(QtWidgets.QFrame.Box)
        self.Video.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Video.setScaledContents(True)
        self.Video.setAlignment(QtCore.Qt.AlignCenter)
        self.Video.setObjectName("Video")
        self.Gaze = QtWidgets.QLabel(self.centralWidget)
        self.Gaze.setGeometry(QtCore.QRect(300, 10, 281, 211))
        self.Gaze.setAutoFillBackground(False)
        self.Gaze.setFrameShape(QtWidgets.QFrame.Box)
        self.Gaze.setScaledContents(True)
        self.Gaze.setAlignment(QtCore.Qt.AlignCenter)
        self.Gaze.setObjectName("Gaze")
        MrGaze.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MrGaze)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 589, 22))
        self.menuBar.setObjectName("menuBar")
        MrGaze.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MrGaze)
        self.mainToolBar.setObjectName("mainToolBar")
        MrGaze.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MrGaze)
        self.statusBar.setObjectName("statusBar")
        MrGaze.setStatusBar(self.statusBar)

        self.retranslateUi(MrGaze)
        self.tabWidget.setCurrentIndex(0)
        self.Intensity_LB_Dial.valueChanged['int'].connect(MrGaze.update_intensity_lb)
        self.Intensity_UB_Dial.valueChanged['int'].connect(MrGaze.update_intensity_ub)
        QtCore.QMetaObject.connectSlotsByName(MrGaze)

    def retranslateUi(self, MrGaze):
        _translate = QtCore.QCoreApplication.translate
        MrGaze.setWindowTitle(_translate("MrGaze", "MrGaze"))
        self.Intensity_LB_Label.setText(_translate("MrGaze", "0"))
        self.Intensity_UB_Label.setText(_translate("MrGaze", "100"))
        self.comboBox.setItemText(0, _translate("MrGaze", "USB iSight"))
        self.comboBox.setItemText(1, _translate("MrGaze", "USB xiQ"))
        self.comboBox.setItemText(2, _translate("MrGaze", "USB Thorlabs"))
        self.comboBox.setItemText(3, _translate("MrGaze", "File"))
        self.pushButton.setText(_translate("MrGaze", "Save Setup"))
        self.label.setText(_translate("MrGaze", "Video Source"))
        self.label_2.setText(_translate("MrGaze", "Video File"))
        self.pushButton_2.setText(_translate("MrGaze", "Freeze"))
        self.toolButton.setText(_translate("MrGaze", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Setup_Tab), _translate("MrGaze", "Setup"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Calibrate_Tab), _translate("MrGaze", "Calibrate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Gaze_Tab), _translate("MrGaze", "Gaze"))
        self.Video.setText(_translate("MrGaze", "BLINK"))
        self.Gaze.setText(_translate("MrGaze", "BLINK"))

