# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mrgaze/gui/MrGaze/mrgaze.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MrGaze(object):
    def setupUi(self, MrGaze):
        MrGaze.setObjectName("MrGaze")
        MrGaze.resize(830, 647)
        MrGaze.setMouseTracking(True)
        MrGaze.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.centralWidget = QtWidgets.QWidget(MrGaze)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 340, 811, 241))
        self.tabWidget.setObjectName("tabWidget")
        self.Setup_Tab = QtWidgets.QWidget()
        self.Setup_Tab.setObjectName("Setup_Tab")
        self.pupilThresholdGroup = QtWidgets.QGroupBox(self.Setup_Tab)
        self.pupilThresholdGroup.setGeometry(QtCore.QRect(10, 0, 91, 131))
        self.pupilThresholdGroup.setObjectName("pupilThresholdGroup")
        self.pupilThresholdDial = QtWidgets.QDial(self.pupilThresholdGroup)
        self.pupilThresholdDial.setGeometry(QtCore.QRect(10, 30, 71, 71))
        self.pupilThresholdDial.setMaximum(100)
        self.pupilThresholdDial.setNotchTarget(5.0)
        self.pupilThresholdDial.setNotchesVisible(True)
        self.pupilThresholdDial.setObjectName("pupilThresholdDial")
        self.pupilThresholdLabel = QtWidgets.QLabel(self.pupilThresholdGroup)
        self.pupilThresholdLabel.setGeometry(QtCore.QRect(10, 100, 71, 20))
        self.pupilThresholdLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.pupilThresholdLabel.setObjectName("pupilThresholdLabel")
        self.glintThresholdGroup = QtWidgets.QGroupBox(self.Setup_Tab)
        self.glintThresholdGroup.setGeometry(QtCore.QRect(110, 0, 91, 131))
        self.glintThresholdGroup.setObjectName("glintThresholdGroup")
        self.glintThresholdLabel = QtWidgets.QLabel(self.glintThresholdGroup)
        self.glintThresholdLabel.setGeometry(QtCore.QRect(10, 100, 71, 20))
        self.glintThresholdLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.glintThresholdLabel.setObjectName("glintThresholdLabel")
        self.glintThresholdDial = QtWidgets.QDial(self.glintThresholdGroup)
        self.glintThresholdDial.setGeometry(QtCore.QRect(10, 30, 71, 71))
        self.glintThresholdDial.setMaximum(100)
        self.glintThresholdDial.setProperty("value", 100)
        self.glintThresholdDial.setNotchTarget(5.0)
        self.glintThresholdDial.setNotchesVisible(True)
        self.glintThresholdDial.setObjectName("glintThresholdDial")
        self.videoSourceGroup = QtWidgets.QGroupBox(self.Setup_Tab)
        self.videoSourceGroup.setGeometry(QtCore.QRect(210, 0, 551, 131))
        self.videoSourceGroup.setObjectName("videoSourceGroup")
        self.videoFileLabel = QtWidgets.QLabel(self.videoSourceGroup)
        self.videoFileLabel.setEnabled(False)
        self.videoFileLabel.setGeometry(QtCore.QRect(20, 60, 41, 21))
        self.videoFileLabel.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.videoFileLabel.setObjectName("videoFileLabel")
        self.videoFileTool = QtWidgets.QToolButton(self.videoSourceGroup)
        self.videoFileTool.setEnabled(False)
        self.videoFileTool.setGeometry(QtCore.QRect(480, 60, 26, 22))
        self.videoFileTool.setObjectName("videoFileTool")
        self.videoSourceCombo = QtWidgets.QComboBox(self.videoSourceGroup)
        self.videoSourceCombo.setGeometry(QtCore.QRect(70, 30, 141, 26))
        self.videoSourceCombo.setObjectName("videoSourceCombo")
        self.videoSourceCombo.addItem("")
        self.videoSourceCombo.addItem("")
        self.videoSourceCombo.addItem("")
        self.videoSourceCombo.addItem("")
        self.videoSourceCombo.addItem("")
        self.videoSourceLabel = QtWidgets.QLabel(self.videoSourceGroup)
        self.videoSourceLabel.setGeometry(QtCore.QRect(10, 30, 51, 21))
        self.videoSourceLabel.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.videoSourceLabel.setObjectName("videoSourceLabel")
        self.videoFileEdit = QtWidgets.QLineEdit(self.videoSourceGroup)
        self.videoFileEdit.setEnabled(False)
        self.videoFileEdit.setGeometry(QtCore.QRect(70, 60, 401, 21))
        self.videoFileEdit.setObjectName("videoFileEdit")
        self.videoFileLabel.raise_()
        self.videoFileTool.raise_()
        self.videoSourceCombo.raise_()
        self.videoSourceLabel.raise_()
        self.videoFileEdit.raise_()
        self.videoControlsBox = QtWidgets.QGroupBox(self.Setup_Tab)
        self.videoControlsBox.setGeometry(QtCore.QRect(10, 130, 191, 71))
        self.videoControlsBox.setObjectName("videoControlsBox")
        self.playButton = QtWidgets.QPushButton(self.videoControlsBox)
        self.playButton.setGeometry(QtCore.QRect(0, 20, 51, 51))
        self.playButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Play.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/icons/Play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playButton.setIcon(icon)
        self.playButton.setIconSize(QtCore.QSize(32, 32))
        self.playButton.setCheckable(True)
        self.playButton.setObjectName("playButton")
        self.groupBox = QtWidgets.QGroupBox(self.Setup_Tab)
        self.groupBox.setGeometry(QtCore.QRect(210, 130, 551, 71))
        self.groupBox.setObjectName("groupBox")
        self.saveSetupButton = QtWidgets.QPushButton(self.groupBox)
        self.saveSetupButton.setGeometry(QtCore.QRect(300, 20, 121, 51))
        self.saveSetupButton.setObjectName("saveSetupButton")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(110, 20, 131, 51))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pupilClassifierLabel = QtWidgets.QLabel(self.groupBox)
        self.pupilClassifierLabel.setGeometry(QtCore.QRect(10, 20, 91, 51))
        self.pupilClassifierLabel.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.pupilClassifierLabel.setObjectName("pupilClassifierLabel")
        self.quitButton = QtWidgets.QPushButton(self.groupBox)
        self.quitButton.setGeometry(QtCore.QRect(420, 20, 121, 51))
        self.quitButton.setObjectName("quitButton")
        self.tabWidget.addTab(self.Setup_Tab, "")
        self.calibrateTab = QtWidgets.QWidget()
        self.calibrateTab.setObjectName("calibrateTab")
        self.tabWidget.addTab(self.calibrateTab, "")
        self.gazeTab = QtWidgets.QWidget()
        self.gazeTab.setObjectName("gazeTab")
        self.tabWidget.addTab(self.gazeTab, "")
        self.gazeView = GazeWidget(self.centralWidget)
        self.gazeView.setGeometry(QtCore.QRect(420, 10, 400, 320))
        self.gazeView.setObjectName("gazeView")
        self.pupilometryView = PupilometryWidget(self.centralWidget)
        self.pupilometryView.setGeometry(QtCore.QRect(10, 10, 400, 320))
        self.pupilometryView.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.pupilometryView.setObjectName("pupilometryView")
        self.gazeView.raise_()
        self.tabWidget.raise_()
        self.pupilometryView.raise_()
        self.gazeView.raise_()
        self.pupilometryView.raise_()
        MrGaze.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MrGaze)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 830, 22))
        self.menuBar.setObjectName("menuBar")
        MrGaze.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MrGaze)
        self.mainToolBar.setObjectName("mainToolBar")
        MrGaze.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MrGaze)
        self.statusBar.setObjectName("statusBar")
        MrGaze.setStatusBar(self.statusBar)

        self.retranslateUi(MrGaze)
        self.tabWidget.setCurrentIndex(0)
        self.glintThresholdDial.valueChanged['int'].connect(self.glintThresholdLabel.setNum)
        self.pupilThresholdDial.valueChanged['int'].connect(self.pupilThresholdLabel.setNum)
        self.glintThresholdDial.valueChanged['int'].connect(self.pupilometryView.change_glint_thresh)
        self.pupilThresholdDial.valueChanged['int'].connect(self.pupilometryView.change_pupil_thresh)
        self.quitButton.clicked.connect(MrGaze.close)
        QtCore.QMetaObject.connectSlotsByName(MrGaze)

    def retranslateUi(self, MrGaze):
        _translate = QtCore.QCoreApplication.translate
        MrGaze.setWindowTitle(_translate("MrGaze", "MrGaze"))
        self.pupilThresholdGroup.setTitle(_translate("MrGaze", "Pupil Threshold"))
        self.pupilThresholdLabel.setText(_translate("MrGaze", "0"))
        self.glintThresholdGroup.setTitle(_translate("MrGaze", "Glint Threshold"))
        self.glintThresholdLabel.setText(_translate("MrGaze", "100"))
        self.videoSourceGroup.setTitle(_translate("MrGaze", "Video Source"))
        self.videoFileLabel.setText(_translate("MrGaze", "File"))
        self.videoFileTool.setText(_translate("MrGaze", "..."))
        self.videoSourceCombo.setCurrentText(_translate("MrGaze", "Default"))
        self.videoSourceCombo.setItemText(0, _translate("MrGaze", "Default"))
        self.videoSourceCombo.setItemText(1, _translate("MrGaze", "USB xiQ"))
        self.videoSourceCombo.setItemText(2, _translate("MrGaze", "USB iSight"))
        self.videoSourceCombo.setItemText(3, _translate("MrGaze", "USB Thorlabs"))
        self.videoSourceCombo.setItemText(4, _translate("MrGaze", "Video File"))
        self.videoSourceLabel.setText(_translate("MrGaze", "Source"))
        self.videoControlsBox.setTitle(_translate("MrGaze", "Video Control"))
        self.groupBox.setTitle(_translate("MrGaze", "Setup"))
        self.saveSetupButton.setText(_translate("MrGaze", "Save Setup"))
        self.comboBox.setItemText(0, _translate("MrGaze", "Manual"))
        self.comboBox.setItemText(1, _translate("MrGaze", "xiQ"))
        self.comboBox.setItemText(2, _translate("MrGaze", "iSight"))
        self.comboBox.setItemText(3, _translate("MrGaze", "Thorlabs"))
        self.pupilClassifierLabel.setText(_translate("MrGaze", "Pupil Classifier"))
        self.quitButton.setText(_translate("MrGaze", "Quit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Setup_Tab), _translate("MrGaze", "Setup"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.calibrateTab), _translate("MrGaze", "Calibrate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.gazeTab), _translate("MrGaze", "Gaze"))

from mrgaze.gazewidget import GazeWidget
from mrgaze.pupilometrywidget import PupilometryWidget
