# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mrgaze/gui/MrGaze/mrgaze.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MrGaze(object):
    def setupUi(self, MrGaze):
        MrGaze.setObjectName("MrGaze")
        MrGaze.resize(800, 606)
        self.centralWidget = QtWidgets.QWidget(MrGaze)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 300, 781, 241))
        self.tabWidget.setObjectName("tabWidget")
        self.Setup_Tab = QtWidgets.QWidget()
        self.Setup_Tab.setObjectName("Setup_Tab")
        self.pupilThresholdGroup = QtWidgets.QGroupBox(self.Setup_Tab)
        self.pupilThresholdGroup.setGeometry(QtCore.QRect(10, 0, 91, 131))
        self.pupilThresholdGroup.setObjectName("pupilThresholdGroup")
        self.Intensity_LB_Dial = QtWidgets.QDial(self.pupilThresholdGroup)
        self.Intensity_LB_Dial.setGeometry(QtCore.QRect(10, 30, 71, 71))
        self.Intensity_LB_Dial.setMaximum(100)
        self.Intensity_LB_Dial.setNotchTarget(5.0)
        self.Intensity_LB_Dial.setNotchesVisible(True)
        self.Intensity_LB_Dial.setObjectName("Intensity_LB_Dial")
        self.Intensity_LB_Label = QtWidgets.QLabel(self.pupilThresholdGroup)
        self.Intensity_LB_Label.setGeometry(QtCore.QRect(10, 100, 71, 20))
        self.Intensity_LB_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Intensity_LB_Label.setObjectName("Intensity_LB_Label")
        self.glintThresholdGroup = QtWidgets.QGroupBox(self.Setup_Tab)
        self.glintThresholdGroup.setGeometry(QtCore.QRect(110, 0, 91, 131))
        self.glintThresholdGroup.setObjectName("glintThresholdGroup")
        self.Intensity_UB_Label = QtWidgets.QLabel(self.glintThresholdGroup)
        self.Intensity_UB_Label.setGeometry(QtCore.QRect(10, 100, 71, 20))
        self.Intensity_UB_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Intensity_UB_Label.setObjectName("Intensity_UB_Label")
        self.Intensity_UB_Dial = QtWidgets.QDial(self.glintThresholdGroup)
        self.Intensity_UB_Dial.setGeometry(QtCore.QRect(10, 30, 71, 71))
        self.Intensity_UB_Dial.setMaximum(100)
        self.Intensity_UB_Dial.setProperty("value", 100)
        self.Intensity_UB_Dial.setNotchTarget(5.0)
        self.Intensity_UB_Dial.setNotchesVisible(True)
        self.Intensity_UB_Dial.setObjectName("Intensity_UB_Dial")
        self.videoSourceGroup = QtWidgets.QGroupBox(self.Setup_Tab)
        self.videoSourceGroup.setGeometry(QtCore.QRect(210, 0, 551, 131))
        self.videoSourceGroup.setObjectName("videoSourceGroup")
        self.videoFileLabel = QtWidgets.QLabel(self.videoSourceGroup)
        self.videoFileLabel.setEnabled(False)
        self.videoFileLabel.setGeometry(QtCore.QRect(20, 60, 41, 21))
        self.videoFileLabel.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.videoFileLabel.setObjectName("videoFileLabel")
        self.videoFileTool = QtWidgets.QToolButton(self.videoSourceGroup)
        self.videoFileTool.setEnabled(False)
        self.videoFileTool.setGeometry(QtCore.QRect(480, 60, 26, 22))
        self.videoFileTool.setObjectName("videoFileTool")
        self.videoSourceCombo = QtWidgets.QComboBox(self.videoSourceGroup)
        self.videoSourceCombo.setGeometry(QtCore.QRect(70, 30, 141, 26))
        self.videoSourceCombo.setObjectName("videoSourceCombo")
        self.videoSourceCombo.addItem("")
        self.videoSourceCombo.addItem("")
        self.videoSourceCombo.addItem("")
        self.videoSourceCombo.addItem("")
        self.videoSourceLabel = QtWidgets.QLabel(self.videoSourceGroup)
        self.videoSourceLabel.setGeometry(QtCore.QRect(10, 30, 51, 21))
        self.videoSourceLabel.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.videoSourceLabel.setObjectName("videoSourceLabel")
        self.videoFileEdit = QtWidgets.QLineEdit(self.videoSourceGroup)
        self.videoFileEdit.setEnabled(False)
        self.videoFileEdit.setGeometry(QtCore.QRect(70, 60, 401, 21))
        self.videoFileEdit.setObjectName("videoFileEdit")
        self.videoControlsBox = QtWidgets.QGroupBox(self.Setup_Tab)
        self.videoControlsBox.setGeometry(QtCore.QRect(10, 130, 251, 71))
        self.videoControlsBox.setObjectName("videoControlsBox")
        self.playButton = QtWidgets.QPushButton(self.videoControlsBox)
        self.playButton.setGeometry(QtCore.QRect(100, 20, 51, 51))
        self.playButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Play.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/icons/Pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playButton.setIcon(icon)
        self.playButton.setIconSize(QtCore.QSize(32, 32))
        self.playButton.setCheckable(True)
        self.playButton.setObjectName("playButton")
        self.restartButton = QtWidgets.QPushButton(self.videoControlsBox)
        self.restartButton.setGeometry(QtCore.QRect(0, 20, 51, 51))
        self.restartButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Restart.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap(":/icons/Restart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restartButton.setIcon(icon1)
        self.restartButton.setIconSize(QtCore.QSize(32, 32))
        self.restartButton.setCheckable(False)
        self.restartButton.setObjectName("restartButton")
        self.rewindButton = QtWidgets.QPushButton(self.videoControlsBox)
        self.rewindButton.setGeometry(QtCore.QRect(50, 20, 51, 51))
        self.rewindButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Rewind.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon2.addPixmap(QtGui.QPixmap(":/icons/Rewind.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rewindButton.setIcon(icon2)
        self.rewindButton.setIconSize(QtCore.QSize(32, 32))
        self.rewindButton.setCheckable(True)
        self.rewindButton.setAutoRepeat(False)
        self.rewindButton.setObjectName("rewindButton")
        self.fastforwardButton = QtWidgets.QPushButton(self.videoControlsBox)
        self.fastforwardButton.setGeometry(QtCore.QRect(150, 20, 51, 51))
        self.fastforwardButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/FastForward.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon3.addPixmap(QtGui.QPixmap(":/icons/FastForward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fastforwardButton.setIcon(icon3)
        self.fastforwardButton.setIconSize(QtCore.QSize(32, 32))
        self.fastforwardButton.setCheckable(True)
        self.fastforwardButton.setObjectName("fastforwardButton")
        self.toEndButton = QtWidgets.QPushButton(self.videoControlsBox)
        self.toEndButton.setGeometry(QtCore.QRect(200, 20, 51, 51))
        self.toEndButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/ToEnd.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon4.addPixmap(QtGui.QPixmap(":/icons/ToEnd.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toEndButton.setIcon(icon4)
        self.toEndButton.setIconSize(QtCore.QSize(32, 32))
        self.toEndButton.setCheckable(False)
        self.toEndButton.setObjectName("toEndButton")
        self.groupBox = QtWidgets.QGroupBox(self.Setup_Tab)
        self.groupBox.setGeometry(QtCore.QRect(280, 130, 481, 71))
        self.groupBox.setObjectName("groupBox")
        self.saveSetupButton = QtWidgets.QPushButton(self.groupBox)
        self.saveSetupButton.setGeometry(QtCore.QRect(360, 20, 121, 51))
        self.saveSetupButton.setObjectName("saveSetupButton")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(110, 20, 131, 51))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pupilClassifierLabel = QtWidgets.QLabel(self.groupBox)
        self.pupilClassifierLabel.setGeometry(QtCore.QRect(10, 20, 91, 51))
        self.pupilClassifierLabel.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.pupilClassifierLabel.setObjectName("pupilClassifierLabel")
        self.tabWidget.addTab(self.Setup_Tab, "")
        self.Calibrate_Tab = QtWidgets.QWidget()
        self.Calibrate_Tab.setObjectName("Calibrate_Tab")
        self.tabWidget.addTab(self.Calibrate_Tab, "")
        self.Gaze_Tab = QtWidgets.QWidget()
        self.Gaze_Tab.setObjectName("Gaze_Tab")
        self.tabWidget.addTab(self.Gaze_Tab, "")
        self.Video = QtWidgets.QLabel(self.centralWidget)
        self.Video.setGeometry(QtCore.QRect(10, 10, 381, 281))
        self.Video.setFrameShape(QtWidgets.QFrame.Box)
        self.Video.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Video.setScaledContents(True)
        self.Video.setAlignment(QtCore.Qt.AlignCenter)
        self.Video.setObjectName("Video")
        self.Gaze = QtWidgets.QLabel(self.centralWidget)
        self.Gaze.setGeometry(QtCore.QRect(410, 10, 381, 281))
        self.Gaze.setAutoFillBackground(False)
        self.Gaze.setFrameShape(QtWidgets.QFrame.Box)
        self.Gaze.setScaledContents(True)
        self.Gaze.setAlignment(QtCore.Qt.AlignCenter)
        self.Gaze.setObjectName("Gaze")
        MrGaze.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MrGaze)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menuBar.setObjectName("menuBar")
        MrGaze.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MrGaze)
        self.mainToolBar.setObjectName("mainToolBar")
        MrGaze.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MrGaze)
        self.statusBar.setObjectName("statusBar")
        MrGaze.setStatusBar(self.statusBar)

        self.retranslateUi(MrGaze)
        self.tabWidget.setCurrentIndex(0)
        self.Intensity_LB_Dial.valueChanged['int'].connect(MrGaze.update_intensity_lb)
        self.Intensity_UB_Dial.valueChanged['int'].connect(MrGaze.update_intensity_ub)
        QtCore.QMetaObject.connectSlotsByName(MrGaze)

    def retranslateUi(self, MrGaze):
        _translate = QtCore.QCoreApplication.translate
        MrGaze.setWindowTitle(_translate("MrGaze", "MrGaze"))
        self.pupilThresholdGroup.setTitle(_translate("MrGaze", "Pupil Threshold"))
        self.Intensity_LB_Label.setText(_translate("MrGaze", "0"))
        self.glintThresholdGroup.setTitle(_translate("MrGaze", "Glint Threshold"))
        self.Intensity_UB_Label.setText(_translate("MrGaze", "100"))
        self.videoSourceGroup.setTitle(_translate("MrGaze", "Video Source"))
        self.videoFileLabel.setText(_translate("MrGaze", "File"))
        self.videoFileTool.setText(_translate("MrGaze", "..."))
        self.videoSourceCombo.setCurrentText(_translate("MrGaze", "USB Camera 0"))
        self.videoSourceCombo.setItemText(0, _translate("MrGaze", "USB Camera 0"))
        self.videoSourceCombo.setItemText(1, _translate("MrGaze", "USB Camera 1"))
        self.videoSourceCombo.setItemText(2, _translate("MrGaze", "USB Camera 2"))
        self.videoSourceCombo.setItemText(3, _translate("MrGaze", "Video File"))
        self.videoSourceLabel.setText(_translate("MrGaze", "Source"))
        self.videoControlsBox.setTitle(_translate("MrGaze", "Video Control"))
        self.groupBox.setTitle(_translate("MrGaze", "Setup"))
        self.saveSetupButton.setText(_translate("MrGaze", "Save Setup"))
        self.comboBox.setItemText(0, _translate("MrGaze", "USB iSight"))
        self.comboBox.setItemText(1, _translate("MrGaze", "USB xiQ"))
        self.comboBox.setItemText(2, _translate("MrGaze", "USB Thorlabs"))
        self.comboBox.setItemText(3, _translate("MrGaze", "File"))
        self.pupilClassifierLabel.setText(_translate("MrGaze", "Pupil Classifier"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Setup_Tab), _translate("MrGaze", "Setup"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Calibrate_Tab), _translate("MrGaze", "Calibrate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Gaze_Tab), _translate("MrGaze", "Gaze"))
        self.Video.setText(_translate("MrGaze", "BLINK"))
        self.Gaze.setText(_translate("MrGaze", "BLINK"))

